FROM debian:latest

USER root

RUN passwd --delete root

RUN apt update -y
RUN apt install pkg-config wget curl lsb-release build-essential software-properties-common gnupg git sudo nano valgrind python3 jq python3-venv procps -y

# CREATE USER

RUN groupadd build
RUN useradd -rm -d /home/build -s /bin/bash -g root -G sudo -u 1001 build
RUN echo "export USER=build" > /etc/profile.d/set_user.sh
RUN passwd --delete build

RUN usermod -a -G sudo build
RUN usermod -a -G build build

RUN mkdir -p "/home/build/rsproject"
RUN chown build:build "/home/build/rsproject"

USER build:build
WORKDIR /home/build

# INSTALL LIVEPROCMON DEPS

RUN python3 -m venv /home/build/.local --system-site-packages
ENV PATH="${PATH}:/home/build/.local/bin"

RUN /home/build/.local/bin/pip install gprof2dot matplotlib pillow

# INSTALL RUST

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ./rustup.rs
RUN chmod +x ./rustup.rs
RUN ./rustup.rs -y
